// assets/src/views/auth/register.vue
<template>
  <div>
    <div v-if="status == 'errored'" class="callout callout-danger">
      <h4>Register fail</h4>
      <p>Verify your data</p>
    </div>

    <div v-if="status == 'success'" class="callout callout-success">
      <h4>Register success</h4>
      <p>Redirecting you to the login page</p>
    </div>

    <form
      method="post"
      @submit.prevent="submit"
      @keyup.13="submit"
    >
      <errorable-input
        v-model="username"
        :errors="errors.username"
        icon="user"
        placeholder="Username"
        type="text"
      />

      <errorable-input
        v-model="email"
        :errors="errors.email"
        icon="envelope"
        placeholder="Email"
        type="email"
      />

      <errorable-input
        v-model="password"
        :errors="errors.password"
        icon="lock"
        placeholder="Password"
        type="password"
      />

      <errorable-input
        v-model="password_confirmation"
        :errors="errors.password_confirmation"
        icon="lock"
        placeholder="Password confirmation"
        type="password"
      />

      <div class="control is-grouped has-addons has-addons-centered">
        <p class="control">
          <router-link :to="{name: 'login'}" class='button is-link'>
            Sign In
          </router-link>
        </p>

        <p class="control">
          <button
            type="submit"
            :disabled="status === 'loading'"
            class="button is-primary"
          >
            Sign Up
          </button>
        </p>
      </div>
    </form>
  </div>
</template>

<script src="./register.js"></script>

// client/routes/auth/Register.jsx
import React, {Component} from 'react';
import {addClass, removeClass} from '../../utils';

export default class Register extends Component {
	componentDidMount() {
		addClass('body', 'login-page');
	}

	componentWillUnmount() {
		removeClass('body', 'login-page');
	}

	render() {
		return (
			<div>
				<p className='login-box-msg'>Sign up</p>

				<form action="../../index.html" method="post">
					<div className="form-group has-feedback">
						<input type="text" className="form-control" placeholder="Full name" />
						<span className="glyphicon glyphicon-user form-control-feedback" />
					</div>
					<div className="form-group has-feedback">
						<input type="email" className="form-control" placeholder="Email" />
						<span className="glyphicon glyphicon-envelope form-control-feedback" />
					</div>
					<div className="form-group has-feedback">
						<input type="password" className="form-control" placeholder="Password" />
						<span className="glyphicon glyphicon-lock form-control-feedback" />
					</div>
					<div className="form-group has-feedback">
						<input type="password" className="form-control" placeholder="Retype password" />
						<span className="glyphicon glyphicon-log-in form-control-feedback" />
					</div>
					<button type="submit" className="btn btn-primary btn-block btn-flat">Register</button>
				</form>
			</div>
		);
	}
}
