// client/routes/Dashboard.jsx
import React from 'react';

export default function Dashboard({children}) {
	return (
		<div className="wrapper">

			<header className="main-header">

				<a href="#" className="logo">
					<span className="logo-mini"><b>P</b>Poker</span>
					<span className="logo-lg"><b>Planning</b>Poker</span>
				</a>

				<nav className="navbar navbar-static-top" role="navigation">
					<div className="navbar-custom-menu">
						<ul className="nav navbar-nav">
						</ul>
					</div>
				</nav>
			</header>
			<aside className="main-sidebar">

				<section className="sidebar">
					<ul className="sidebar-menu">
						<li className="header">MENU</li>
						<li className="active"><a href="#"><i className="fa fa-link"></i> <span>Link</span></a></li>
						<li><a href="#"><i className="fa fa-link"></i> <span>Another Link</span></a></li>
						<li className="treeview">
							<a href="#"><i className="fa fa-link"></i> <span>Multilevel</span>
								<span className="pull-right-container">
									<i className="fa fa-angle-left pull-right"></i>
								</span>
							</a>
							<ul className="treeview-menu">
								<li><a href="#">Link in level 2</a></li>
								<li><a href="#">Link in level 2</a></li>
							</ul>
						</li>
					</ul>
				</section>
			</aside>

			<div className="content-wrapper" style={{minHeight: window.innerHeight}}>
				<section className="content-header">
					<h1>
						Page Header
						<small>Optional description</small>
					</h1>
				</section>

				<section className="content">

					{children}

				</section>
			</div>

			<footer className="main-footer">
				<div className="pull-right hidden-xs">
					Anything you want
				</div>
				<strong>Copyright &copy; 2016 <a href="#">Company</a>.</strong> All rights reserved.
			</footer>

			<aside className="control-sidebar control-sidebar-dark">
				<ul className="nav nav-tabs nav-justified control-sidebar-tabs">
					<li className="active"><a href="#" data-toggle="tab"><i className="fa fa-home"></i></a></li>
					<li><a href="#" data-toggle="tab"><i className="fa fa-gears"></i></a></li>
				</ul>
				<div className="tab-content">
					<div className="tab-pane active" id="control-sidebar-home-tab">
						<h3 className="control-sidebar-heading">Recent Activity</h3>
						<ul className="control-sidebar-menu">
							<li>
								<a href="#">
									<i className="menu-icon fa fa-birthday-cake bg-red"></i>

									<div className="menu-info">
										<h4 className="control-sidebar-subheading">Langdon's Birthday</h4>

										<p>Will be 23 on April 24th</p>
									</div>
								</a>
							</li>
						</ul>

						<h3 className="control-sidebar-heading">Tasks Progress</h3>
						<ul className="control-sidebar-menu">
							<li>
								<a href="#">
									<h4 className="control-sidebar-subheading">
										Custom Template Design
										<span className="pull-right-container">
											<span className="label label-danger pull-right">70%</span>
										</span>
									</h4>

									<div className="progress progress-xxs">
										<div className="progress-bar progress-bar-danger" style={{width: '70%'}}></div>
									</div>
								</a>
							</li>
						</ul>

					</div>
					<div className="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
					<div className="tab-pane" id="control-sidebar-settings-tab">
						<form method="post">
							<h3 className="control-sidebar-heading">General Settings</h3>

							<div className="form-group">
								<label className="control-sidebar-subheading">
									Report panel usage
									<input type="checkbox" className="pull-right" checked />
								</label>

								<p>
									Some information about this general settings option
								</p>
							</div>
						</form>
					</div>
				</div>
			</aside>
			<div className="control-sidebar-bg"></div>
		</div>
	);
}

// web/static/js/layouts/dashboard.vue
<template lang="pug">
  .wrapper
    header.main-header
      router-link(':to'='{name: "home"}').logo
        span.logo-mini #[b P]Poker
        span.logo-lg #[b Planning]Poker

      nav.navbar.navbar-static-top(role="navigation")
        .navbar-custom-menu
          ul.nav.navbar-menu

    sidebar

    .content-wrapper(':style'='wrapperStyle')
      section.content-header
        h1 {{page.title}}
          small(v-if='page.description !== null') {{page.description}}
      section.content
        router-view.nested-child
    footer.main-footer
      .pull-right.hidden-xs
        | Anything you want
      strong
        | Copyright © 2016
        a(href='#') Company
        | .
      |  All rights reserved.
    aside.control-sidebar.control-sidebar-dark
      ul.nav.nav-tabs.nav-justified.control-sidebar-tabs
        li.active
          a(href='#', data-toggle='tab')
            i.fa.fa-home
        li
          a(href='#', data-toggle='tab')
            i.fa.fa-gears
      .tab-content
        #control-sidebar-home-tab.tab-pane.active
          h3.control-sidebar-heading Recent Activity
          ul.control-sidebar-menu
            li
              a(href='#')
                i.menu-icon.fa.fa-birthday-cake.bg-red
                .menu-info
                  h4.control-sidebar-subheading Langdon's Birthday
                  p Will be 23 on April 24th
          h3.control-sidebar-heading Tasks Progress
          ul.control-sidebar-menu
            li
              a(href='#')
                h4.control-sidebar-subheading
                  | Custom Template Design
                  span.pull-right-container
                    span.label.label-danger.pull-right 70%
                .progress.progress-xxs
                  .progress-bar.progress-bar-danger(style='{{width:')
        #control-sidebar-stats-tab.tab-pane Stats Tab Content
        #control-sidebar-settings-tab.tab-pane
          form(method='post')
            h3.control-sidebar-heading General Settings
            .form-group
              label.control-sidebar-subheading
                | Report panel usage
                input.pull-right(type='checkbox', checked='')
              p
                | Some information about this general settings option
    .control-sidebar-bg &nbsp;
</template>

<script>
  import {Sidebar} from 'app/components';

  export default {
    name: 'DashBoard',

    components: {
      sidebar: Sidebar,
    },

    computed: {
      page() {
        return this.$store.state.page;
      },
      wrapperStyle() {
        return {
          minHeight: `${window.innerHeight}px`
        }
      }
    },

    created() {
      this.$store.commit('page/set', {title: 'HomePage'});
    }
  }
</script>
